# Generated by Django 3.1 on 2020-09-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('rate', models.IntegerField(max_length=10)),
                ('review', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='device_default.png', upload_to='')),
            ],
        ),
    ]
