# Generated by Django 3.1 on 2020-09-29 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('university', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('rate', models.IntegerField()),
                ('review', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='device_default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=100)),
                ('Answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_time', models.DateTimeField()),
                ('Finish_time', models.DateTimeField()),
                ('Device', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.devices')),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experiments',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('experiment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.devices')),
                ('user_exp', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
