# Generated by Django 3.1 on 2020-09-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='1900-01-01', verbose_name='date of birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
