# Generated by Django 3.1 on 2020-09-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='user e-mail')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('university', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('country', models.CharField(max_length=30)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('institute', 'Institute')], default='student', max_length=10)),
            ],
        ),
    ]
