# Generated by Django 3.1 on 2020-09-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200929_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('S', 'Student'), ('I', 'Institute')], default='S', max_length=1),
        ),
    ]
