# Generated by Django 3.1 on 2020-10-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201001_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='id',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
