# Generated by Django 3.1 on 2020-09-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Institute_id',
            field=models.IntegerField(default=00000),
            preserve_default=False,
        ),
    ]
