# Generated by Django 3.1 on 2020-09-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_experiments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiments',
            old_name='device_id',
            new_name='device_name',
        ),
        migrations.AlterField(
            model_name='devices',
            name='device_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
