# Generated by Django 3.1 on 2020-09-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200913_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='FQA',
            fields=[
                ('Question', models.CharField(max_length=100)),
                ('Answer', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_time', models.DateTimeField()),
                ('Finish_time', models.DateTimeField()),
            ],
        ),
    ]
