# Generated by Django 3.1 on 2020-09-14 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fqa_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FQA',
            new_name='FAQ',
        ),
    ]
