# Generated by Django 3.1 on 2020-09-14 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200914_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Device',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.devices'),
        ),
    ]
